### ISSUE TITLE
Building KNN version of the model

### ISSUE THREAD

**Issue by rivermd** [Workspace-Recommendation-Engine/reco_eng#15]
This will involve coding the core KNN engine and comparing results to the original SAR model we used

**Comment by rivermd** [comment]
- [ ] finish draft of KNN 
- [ ] implement cold start solution to KNN
- [ ] document the code (comments, captions, etc)
- [ ] compare results to SAR

**Comment by rivermd** [comment]
Just finished the draft of the KNN, will work on the documentation for it tomorrow as well as talking with Farah about how we can implement the cold start solution within it. Then we can compare the results to the SAR once we have the cold start solution implemented in the SAR model as well.

**Comment by farahabuatiyeh** [comment]
Thank you for the update on the progress of the KNN draft. It's great to hear that you have completed the draft and are now working on the documentation. As you mentioned, let's discuss the implementation of the cold start solution today.

I want to make sure that we have a solid plan for implementing the cold start solution in both the KNN and SAR models. It's important that we consider the user experience and ensure that our models provide accurate recommendations for new users.

It's important that we have a clear timeline for when we expect to have the cold start solution implemented in both models so that we can plan accordingly.

Thank you for your hard work on this project.
